### ISSUE TITLE
Consider switching `rslex-pachyderm` to use `rslex-http-stream` rather than the copied over `rslex-http-stream-old`

### ISSUE THREAD

**Issue by lukemarsden** [pachyderm/aml#17]
In the _rebase from hell_ (TM), I ended up just copying over the old `rslex-http-stream` and renaming it. This is cruft which should probably be removed before we open the PR.

**Comment by albscui** [comment]
We can do better than this, and eliminate `pachyderm_stream` as well:

Step 1 - eliminate pachyderm_stream by changing all references to pachyderm_stream to point to rslex_http_stream_old
        - delete pachyderm_stream
Step 2 - change usage of http_stream_old to use http_stream
        - delete http_stream_old
