### ISSUE TITLE
Update README with instruction on how to activate private preview in your account (needs collaboration with Microsoft!)

### ISSUE THREAD

**Issue by lukemarsden** [pachyderm/aml#39]
Andrei mentioned that the current instructions in the README in this repo won't actually work without Microsoft allowlisting the custom datastores feature for a user (I think). Work with Microsoft to figure out a workflow for enabling this when we have a private preview user who wants to try it out, and update the README accordingly.

**Comment by albscui** [comment]
Done. https://github.com/pachyderm/aml#step-0---enable-custom-datastores-on-your-azure-subscription-id
