### ISSUE TITLE
Support migrating data from ADLS Gen2 to Pachyderm

### ISSUE THREAD

**Issue by albscui** [pachyderm/aml#54]
We want to support Azure customers who use ADSL Gen2.

As a first pass, we can use Pachyderm pipelines to ingest data from ADLS Gen2. The pipeline would be a cron pipeline that runs on a cadence, and has authority to access ADLS Gen2.

After this is implemented, we can work on a more sophisticated variant described here https://github.com/pachyderm/aml/issues/41

**Comment by JoeyZwicker** [comment]
> The pipeline would be a cron pipeline that runs on a cadence, and has authority to access ADLS Gen2.
This might be a good MVP first past. 

A future version of this should be a spout that looks for ADLS Gen2 event triggers (see AWs SQS example for comparison) and ingests that data into Pachyderm. I believe the current version of ADLS is missing some features -- it can event on new file adds, but not modifications or deletions. <-- my info on this may be out of date though. If ADLS needs to add new features, ping me with specifics as I know the VP or Product on ADLS and can try to get the feature escalated.
